# Generated by Django 4.2.7 on 2023-11-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_book_total_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_period',
            new_name='rental_days',
        ),
    ]
