# Generated by Django 4.2.7 on 2023-11-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/%d/%m/%y')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
