# Generated by Django 4.2.7 on 2023-11-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ss_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ss',
            new_name='product',
        ),
    ]
