# Generated by Django 4.2.7 on 2023-11-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_ss_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Ahmed',
        ),
    ]
