# Generated by Django 4.2.7 on 2023-11-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_ahmed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ahmed',
            new_name='product',
        ),
    ]
