# Generated by Django 4.2.7 on 2023-11-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'name'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('eleictric', 'eleictric'), ('price', 'price'), ('food', 'food'), ('sport', 'sport')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(blank=True, default='True', null=True, verbose_name='write the compline'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/19/11/23/cv.PNG', upload_to='images/%d/%m/%y'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='True', max_length=100, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22.5, max_digits=6),
        ),
    ]
