# Generated by Django 4.2.7 on 2023-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_options_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('eleictric', 'eleictric'), ('price', 'price'), ('food', 'food'), ('sport', 'sport')], default='price', max_length=35, null=True),
        ),
    ]
